# syntax=docker/dockerfile:1.5-labs

ARG GIT_TAG=${GIT_TAG:-main}

FROM python:3.10-slim AS app

ARG GIT_TAG

COPY --from=ceramicwhite/gotty /usr/bin/gotty /bin/gotty

ENV PIP_NO_CACHE_DIR=yes \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    HOME=/app \
    PATH="${PATH}:/app/.local/bin"

WORKDIR /app

ADD https://github.com/AntonOsika/gpt-engineer.git#${GIT_TAG} .

RUN pip install --upgrade pip && \
    pip install -e .

EXPOSE 3000

ENTRYPOINT ["gotty", "--port", "3000", "--permit-write", "--title-format", "GPT-ENGINEER", "python", "-m", "gpt_engineer.main"]
CMD ["projects/example"]
